version: 0.2

run-as: root

env:

  parameter-store:
    GIT_USER: "AS-GIT-USERNAME"
    GIT_PASS: "AS-GIT-SECURE-PASSWORD"
    NPM_PASS: "AS-NPM-PASSWORD"

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Entered the install phase ...
      - git config --global credential.helper 'store'
      - echo "https://$GIT_USER:$GIT_PASS@github.com" > ~/.git-credentials
      - git clone https://$GIT_USER:$GIT_PASS@$TEST_GIT_REPO tempRepo
      - cd tempRepo
      - git checkout $CODEBUILD_RESOLVED_SOURCE_VERSION
      - cd ..
      - cp -Rf tempRepo/.git .
  pre_build:
    commands:
      - echo Entered the pre build phase...
  build:
    commands:
      - echo Entered the build phase...
      - git branch
      - npm install 
      - npm run release
  post_build:
    commands:
      - echo Entered the post build phase...
      #- rm -Rf node_modules build
      - echo Done!
